title: Mandar Chitre
description: >- # this means to ignore newlines until "baseurl:"
  Mandar Chitre's homepage
baseurl: "/"
url: "http://www.chitre.net/"
favicon: /favicon.ico
#google_analytics: UA-49024852-2
footer_menu: footer
remote_theme: chrisrhymes/bulma-clean-theme

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - github-pages
